name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make shared-Linux
      run: make shared-Linux
    - name: cp lib
      run: sudo cp lib/libjsonval.so /usr/local/lib
    - name: ld conf
      run: sudo ldconfig
    - name: make
      run: make
    - name: test
      run: build/bvald -h
    - name: make clean
      run: make clean
